### PR TITLE
Include anchor cells in featurization

### PR DESCRIPTION
**Pull request by MagdalenaMat**
I added a binary flag enabling users to compute features such that anchors are considered a part of the neighborhood.

### CODE REVIEW

**Comment by MagdalenaMat** [comment]
@vjojic I added the test you suggested and an exception in the featurization function when there are no neighbours to compute features from.

**Comment by z-chen** [comment]
Hi @MagdalenaMat, thanks for the change, it looks great!

One minor thing: we try to be pep8 compliant and not leave spaces in keyword argument assignment 

E.g.,

```
def featurize_samples(sample_dfs, neighborhood_feature_fn, radius, is_anchor_col,
                      x_col, y_col, z_col=None, n_processes=None, include_anchors=False):
```

instead of 

```
def featurize_samples(sample_dfs, neighborhood_feature_fn, radius, is_anchor_col,
                      x_col, y_col, z_col=None, n_processes=None, include_anchors = False):
```

Would you mind making that minor change?

Other than that, LGTM!

Thanks,
Zhenghao

**Comment by MagdalenaMat** [comment]
Hi @z-chen I fixed it. Thanks!

**Comment by z-chen** [comment]
Thank you!

**Pull request merged**
